package views;

import controllers.CandidatoController;
import controllers.EmpleoController;
import controllers.PostulacionController;
import core.services.ResponseService;
import core.utils.UsuarioThreadLocal;
import core.utils.Util;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Candidato;
import models.EstudioAcademico;
import models.ExperienciaLaboral;
import models.Postulacion;

public class ViewMenuCandidato extends javax.swing.JFrame {

    Util util = new Util();
    Login login = new Login();
    CandidatoController candidatoController = new CandidatoController();
    EmpleoController empleoController = new EmpleoController();
    PostulacionController postulacionController = new PostulacionController();

    public ViewMenuCandidato() {
        initComponents();
        mostrarDatosBasicos();
        listarEstudiosAcademicos();
        listarExperienciaLaboral();
        listarEmpleosCandidatos();
        listarPostulaciones();
    }

    final public void mostrarDatosBasicos() {

        txtNombres.setText(UsuarioThreadLocal.get().getNombres());
        txtApellidos.setText(UsuarioThreadLocal.get().getApellidos());
        txtEmail.setText(UsuarioThreadLocal.get().getUsername());
    }

    final public void listarEstudiosAcademicos() {
        EstudioAcademico estudioAcademico = new EstudioAcademico();
        estudioAcademico.setIdCandidato(UsuarioThreadLocal.get().getIdCandidato());

        final ResponseService<List<Object[]>> response = candidatoController.listarEstudiosAcademicos(estudioAcademico);

        if (response.isSuccess()) {
            List<Object[]> items = response.getResult();

            DefaultTableModel modelo = (DefaultTableModel) tblListaEstudiosAcademicos.getModel();
            modelo.setRowCount(0);

            // Agregar los datos al modelo
            for (Object[] item : items) {
                modelo.addRow(item);
            }
        } else {
            util.alertMessage("Error al obtener estudios academicos", true);
        }
    }

    final public void listarExperienciaLaboral() {
        ExperienciaLaboral experienciaLaboral = new ExperienciaLaboral();
        experienciaLaboral.setIdCandidato(UsuarioThreadLocal.get().getIdCandidato());

        final ResponseService<List<Object[]>> response = candidatoController.listarExperienciasLaborales(experienciaLaboral);

        if (response.isSuccess()) {
            List<Object[]> items = response.getResult();

            DefaultTableModel modelo = (DefaultTableModel) TablaExperiencia.getModel();
            modelo.setRowCount(0);

            // Agregar los datos al modelo
            for (Object[] item : items) {
                modelo.addRow(item);
            }
        } else {
            util.alertMessage("Error al obtener estudios academicos", true);
        }
    }

    final public void listarEmpleosCandidatos() {

        final ResponseService<List<Object[]>> response = empleoController.listarEmpleosCandidatos();

        if (response.isSuccess()) {
            List<Object[]> items = response.getResult();

            DefaultTableModel modelo = (DefaultTableModel) tblEmpleos.getModel();
            modelo.setRowCount(0);

            // Agregar los datos al modelo
            for (Object[] item : items) {
                modelo.addRow(item);
            }
        } else {
            util.alertMessage("Error al obtener empleos", true);
        }
    }

    final public void listarPostulaciones() {
        Postulacion postulacion = new Postulacion();
        postulacion.setIdCandidato(UsuarioThreadLocal.get().getIdCandidato());

        final ResponseService<List<Object[]>> response = postulacionController.listarPostulaciones(postulacion.toString());

        if (response.isSuccess()) {
            List<Object[]> items = response.getResult();

            DefaultTableModel modelo = (DefaultTableModel) tblMisPostulaciones.getModel();
            modelo.setRowCount(0);

            // Agregar los datos al modelo
            for (Object[] item : items) {
                modelo.addRow(item);
            }
        } else {
            util.alertMessage("Error al obtener estudios academicos", true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        Celular = new javax.swing.JTextField();
        Genero = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        FechaNacimiento = new javax.swing.JTextField();
        EstadoCivil = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        Estudios = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        EstudiosFechaInicio = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        EstudiosFechaFin = new javax.swing.JTextField();
        btnRegistrarEstudioAcademico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Experiencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ExperienciaFechaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ExperienciaFechaFin = new javax.swing.JTextField();
        AgregarExperiencia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Aptitudes = new javax.swing.JTextField();
        AgregarAptitud = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        QuitarExperiencia = new javax.swing.JButton();
        QuitarEstudios = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        AgregarCurriculum = new javax.swing.JButton();
        CurriculumArchivo = new javax.swing.JLabel();
        QuitarCurriculum = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        AgregarCertificado = new javax.swing.JButton();
        QuitarCertificado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListaEstudiosAcademicos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaExperiencia = new javax.swing.JTable();
        QuitarAptitud = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcionEL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAptitudes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMisPostulaciones = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPostulacionesDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEmpleos = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtEmpleoDescripcion = new javax.swing.JTextArea();
        btnPostularEmpleos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setText("Nombre(s)");

        jLabel19.setText("Apellido(s)");

        jLabel20.setText("Email");

        jLabel21.setText("Celular");

        txtNombres.setBackground(new java.awt.Color(229, 229, 229));

        txtApellidos.setBackground(new java.awt.Color(229, 229, 229));

        txtEmail.setBackground(new java.awt.Color(229, 229, 229));

        Celular.setBackground(new java.awt.Color(229, 229, 229));

        Genero.setBackground(new java.awt.Color(229, 229, 229));
        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "M", "F" }));

        jLabel24.setText("DNI");

        jLabel25.setText("Fecha de Nacimiento");

        jLabel26.setText("Género");

        jLabel27.setText("Estado Civil");

        DNI.setBackground(new java.awt.Color(229, 229, 229));

        FechaNacimiento.setBackground(new java.awt.Color(229, 229, 229));

        EstadoCivil.setBackground(new java.awt.Color(229, 229, 229));
        EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "soltero", "casado", "viudo" }));

        jLabel28.setText("Grado");

        Estudios.setBackground(new java.awt.Color(229, 229, 229));
        Estudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "tecnico", "universitario" }));

        jLabel29.setText("Fecha Inicio");

        EstudiosFechaInicio.setBackground(new java.awt.Color(229, 229, 229));

        jLabel30.setText("Fecha Final");

        EstudiosFechaFin.setBackground(new java.awt.Color(229, 229, 229));

        btnRegistrarEstudioAcademico.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarEstudioAcademico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarEstudioAcademico.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEstudioAcademico.setText("AGREGAR");
        btnRegistrarEstudioAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstudioAcademicoActionPerformed(evt);
            }
        });

        jLabel1.setText("Título");

        Experiencia.setBackground(new java.awt.Color(229, 229, 229));
        Experiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExperienciaActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha Inicio");

        ExperienciaFechaInicio.setBackground(new java.awt.Color(229, 229, 229));

        jLabel3.setText("Fecha Final");

        ExperienciaFechaFin.setBackground(new java.awt.Color(229, 229, 229));

        AgregarExperiencia.setBackground(new java.awt.Color(102, 102, 102));
        AgregarExperiencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarExperiencia.setForeground(new java.awt.Color(255, 255, 255));
        AgregarExperiencia.setText("AGREGAR");
        AgregarExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarExperienciaActionPerformed(evt);
            }
        });

        jLabel4.setText("Aptitudes");

        Aptitudes.setBackground(new java.awt.Color(229, 229, 229));

        AgregarAptitud.setBackground(new java.awt.Color(102, 102, 102));
        AgregarAptitud.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarAptitud.setForeground(new java.awt.Color(255, 255, 255));
        AgregarAptitud.setText("AGREGAR");
        AgregarAptitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAptitudActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("GUARDAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        QuitarExperiencia.setBackground(new java.awt.Color(102, 102, 102));
        QuitarExperiencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuitarExperiencia.setForeground(new java.awt.Color(255, 255, 255));
        QuitarExperiencia.setText("QUITAR");

        QuitarEstudios.setBackground(new java.awt.Color(102, 102, 102));
        QuitarEstudios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuitarEstudios.setForeground(new java.awt.Color(255, 255, 255));
        QuitarEstudios.setText("QUITAR");
        QuitarEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarEstudiosActionPerformed(evt);
            }
        });

        jLabel22.setText("Curriculum Vitae");

        AgregarCurriculum.setBackground(new java.awt.Color(102, 102, 102));
        AgregarCurriculum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarCurriculum.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCurriculum.setText("AGREGAR");

        CurriculumArchivo.setText("archivo");

        QuitarCurriculum.setBackground(new java.awt.Color(102, 102, 102));
        QuitarCurriculum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuitarCurriculum.setForeground(new java.awt.Color(255, 255, 255));
        QuitarCurriculum.setText("QUITAR");
        QuitarCurriculum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarCurriculumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(AgregarCurriculum)
                .addGap(18, 18, 18)
                .addComponent(QuitarCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CurriculumArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(AgregarCurriculum)
                    .addComponent(QuitarCurriculum)
                    .addComponent(CurriculumArchivo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel23.setText("Certificados");

        AgregarCertificado.setBackground(new java.awt.Color(102, 102, 102));
        AgregarCertificado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarCertificado.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCertificado.setText("AGREGAR");

        QuitarCertificado.setBackground(new java.awt.Color(102, 102, 102));
        QuitarCertificado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuitarCertificado.setForeground(new java.awt.Color(255, 255, 255));
        QuitarCertificado.setText("QUITAR");

        tblListaEstudiosAcademicos.setBackground(new java.awt.Color(229, 229, 229));
        tblListaEstudiosAcademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Descripción", "Fecha Inicio", "Fecha Final", "Grado"
            }
        ));
        jScrollPane3.setViewportView(tblListaEstudiosAcademicos);

        TablaExperiencia.setBackground(new java.awt.Color(229, 229, 229));
        TablaExperiencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Descripción", "Empresa", "Fecha Inicio", "Fecha Final"
            }
        ));
        jScrollPane6.setViewportView(TablaExperiencia);

        QuitarAptitud.setBackground(new java.awt.Color(102, 102, 102));
        QuitarAptitud.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuitarAptitud.setForeground(new java.awt.Color(255, 255, 255));
        QuitarAptitud.setText("QUITAR");

        jLabel5.setText("Descripción");

        txtDescripcionEL.setBackground(new java.awt.Color(226, 226, 226));

        jLabel6.setText("Título");

        txtTitulo.setBackground(new java.awt.Color(229, 229, 229));

        txtDescripcion.setBackground(new java.awt.Color(229, 229, 229));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        jLabel8.setText("Descripción");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Estudios Académicos");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Experiencia Laboral");

        jLabel10.setText("Empresa");

        txtEmpresa.setBackground(new java.awt.Color(226, 226, 226));

        txtAreaAptitudes.setBackground(new java.awt.Color(229, 229, 229));
        txtAreaAptitudes.setColumns(20);
        txtAreaAptitudes.setRows(5);
        jScrollPane2.setViewportView(txtAreaAptitudes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Aptitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AgregarAptitud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuitarAptitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(159, 159, 159)
                                .addComponent(jLabel19))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(DNI)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel6))
                                .addGap(46, 46, 46)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EstudiosFechaInicio)
                            .addComponent(EstudiosFechaFin))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRegistrarEstudioAcademico)
                                .addGap(18, 18, 18)
                                .addComponent(QuitarEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Estudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDescripcion)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20))
                            .addComponent(jLabel26)
                            .addComponent(txtEmail)
                            .addComponent(Genero, 0, 140, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27)
                            .addComponent(Celular)
                            .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgregarCertificado)
                        .addGap(18, 18, 18)
                        .addComponent(QuitarCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(Experiencia))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ExperienciaFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(ExperienciaFechaInicio)))
                            .addComponent(txtDescripcionEL)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AgregarExperiencia)
                                .addGap(18, 18, 18)
                                .addComponent(QuitarExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(Estudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EstudiosFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(EstudiosFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExperienciaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExperienciaFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDescripcionEL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuitarExperiencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgregarExperiencia)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuitarEstudios)
                            .addComponent(btnRegistrarEstudioAcademico))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuitarCertificado)
                    .addComponent(AgregarCertificado)
                    .addComponent(jLabel23)
                    .addComponent(QuitarAptitud)
                    .addComponent(AgregarAptitud)
                    .addComponent(Aptitudes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("Mis Datos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField13.setBackground(new java.awt.Color(229, 229, 229));

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("BUSCAR");

        tblMisPostulaciones.setBackground(new java.awt.Color(229, 229, 229));
        tblMisPostulaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Empresa", "Sueldo", "Modalidad", "Descripcion", "Estado", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMisPostulaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMisPostulacionesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblMisPostulaciones);

        txtPostulacionesDescripcion.setBackground(new java.awt.Color(229, 229, 229));
        txtPostulacionesDescripcion.setColumns(20);
        txtPostulacionesDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtPostulacionesDescripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane1))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mis Postulaciones", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jTextField15.setBackground(new java.awt.Color(229, 229, 229));

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("BUSCAR");

        tblEmpleos.setBackground(new java.awt.Color(229, 229, 229));
        tblEmpleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Empresa", "Sueldo", "Modalidad", "Descripcion", "Fecha Creado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblEmpleos);

        txtEmpleoDescripcion.setBackground(new java.awt.Color(229, 229, 229));
        txtEmpleoDescripcion.setColumns(20);
        txtEmpleoDescripcion.setRows(5);
        jScrollPane7.setViewportView(txtEmpleoDescripcion);

        btnPostularEmpleos.setBackground(new java.awt.Color(102, 102, 102));
        btnPostularEmpleos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPostularEmpleos.setForeground(new java.awt.Color(255, 255, 255));
        btnPostularEmpleos.setText("POSTULAR");
        btnPostularEmpleos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostularEmpleosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPostularEmpleos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPostularEmpleos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleos", jPanel3);

        jMenuBar1.setBorder(null);

        jMenu1.setText("Cerrar Sesión");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        util.centerOnScreen(login, true);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void QuitarCurriculumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarCurriculumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitarCurriculumActionPerformed

    private void QuitarEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitarEstudiosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String email = txtEmail.getText();
        String celular = Celular.getText();
        String dni = DNI.getText();
        String fecha_nac = FechaNacimiento.getText();
        String género = Genero.getSelectedItem().toString();
        String estado_civil = EstadoCivil.getSelectedItem().toString();

        try {
            CandidatoController candidatoController = new CandidatoController();
            Candidato candidato = new Candidato();

            // Candidato
            candidato.setNombre(nombres);
            candidato.setApellidos(apellidos);

            candidato.setTelefono(celular);
            candidato.setNroDocumento(dni);
            candidato.setFechaNacimiento(fecha_nac);
            candidato.setSexo(género);
            candidato.setEstadoCivil(estado_civil);

            candidatoController.registrarCandidato(candidato);
            System.out.println("Candidato creado exitosamente.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR TU USUARIO" + e);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRegistrarEstudioAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstudioAcademicoActionPerformed

        String titulo = txtTitulo.getText();
        String grado = Estudios.getSelectedItem().toString();
        String descripcion = txtDescripcion.getText();
        String fecha_ini = EstudiosFechaInicio.getText();
        String fecha_fin = EstudiosFechaFin.getText();

        EstudioAcademico estudioAcademico = new EstudioAcademico();
        estudioAcademico.setIdCandidato(UsuarioThreadLocal.get().getIdCandidato());
        estudioAcademico.setTitulo(titulo);
        estudioAcademico.setGrado(grado);
        estudioAcademico.setDescripcion(descripcion);
        estudioAcademico.setFechaInicio(fecha_ini);
        estudioAcademico.setFechaFin(fecha_fin);

        ResponseService<Boolean> response = candidatoController.registrarEstudioAcademico(estudioAcademico);
        System.out.println("Success: " + response.isSuccess());
        System.out.println("Mensaje: " + response.getMessage());
        System.out.println("Resultado: " + response.getResult());

        if (response.isSuccess()) {
            util.alertMessage(response.getMessage());
            listarEstudiosAcademicos();
            txtTitulo.setText("");
            Estudios.setSelectedItem(0);
            txtDescripcion.setText("");
            EstudiosFechaInicio.setText("");
            EstudiosFechaFin.setText("");
        } else {
            util.alertMessage("Error al registrar", true);
        }
    }//GEN-LAST:event_btnRegistrarEstudioAcademicoActionPerformed

    private void AgregarExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarExperienciaActionPerformed
        String titulo = Experiencia.getText();
        String empresa = txtEmpresa.getText();
        String fecha_ini = ExperienciaFechaInicio.getText();
        String fecha_fin = ExperienciaFechaFin.getText();
        String descripcion = txtDescripcionEL.getText();

        ExperienciaLaboral experienciaLaboral = new ExperienciaLaboral();
        experienciaLaboral.setIdCandidato(UsuarioThreadLocal.get().getIdCandidato());
        experienciaLaboral.setTitulo(titulo);
        experienciaLaboral.setEmpresa(empresa);
        experienciaLaboral.setFechaInicio(fecha_ini);
        experienciaLaboral.setFechaFin(fecha_fin);
        experienciaLaboral.setDescripcion(descripcion);

        ResponseService<Boolean> response = candidatoController.registrarExperienciaLaboral(experienciaLaboral);
        System.out.println("Success: " + response.isSuccess());
        System.out.println("Mensaje: " + response.getMessage());
        System.out.println("Resultado: " + response.getResult());

        if (response.isSuccess()) {
            util.alertMessage(response.getMessage());
            listarExperienciaLaboral();
            Experiencia.setText("");
            txtEmpresa.setText("");
            ExperienciaFechaInicio.setText("");
            ExperienciaFechaFin.setText("");
            txtDescripcionEL.setText("");
        } else {
            util.alertMessage("Error al registrar", true);
        }


    }//GEN-LAST:event_AgregarExperienciaActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void ExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExperienciaActionPerformed

    private void AgregarAptitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAptitudActionPerformed

    }//GEN-LAST:event_AgregarAptitudActionPerformed

    private void tblEmpleosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleosMouseClicked
        System.out.println("clickeando");

        int fila = tblEmpleos.getSelectedRow();
        System.out.println("La fila es: " + fila);

        if (fila != -1) {
            Object titulo = tblEmpleos.getValueAt(fila, 1);
            Object empresa = tblEmpleos.getValueAt(fila, 2);
            Object sueldo = tblEmpleos.getValueAt(fila, 3);
            Object modalidad = tblEmpleos.getValueAt(fila, 4);
            Object descripcion = tblEmpleos.getValueAt(fila, 5);

            StringBuilder descripcionCompleta = new StringBuilder();
            descripcionCompleta.append("================== DESCRIPCIÓN DEL EMPLEO ==================\n\n");
            descripcionCompleta.append("Titulo:  ").append(titulo != null ? titulo.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Empresa:  ").append(empresa != null ? empresa.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Sueldo:  ").append(sueldo != null ? sueldo.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Modalidad:  ").append(modalidad != null ? modalidad.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Descripción:  ").append(descripcion != null ? descripcion.toString() : "No disponible").append("\n\n");

            txtEmpleoDescripcion.setText(descripcionCompleta.toString());
        }
    }//GEN-LAST:event_tblEmpleosMouseClicked

    private void btnPostularEmpleosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostularEmpleosActionPerformed
    
    }//GEN-LAST:event_btnPostularEmpleosActionPerformed

    private void tblMisPostulacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMisPostulacionesMouseClicked
    System.out.println("clickeando");

        int fila = tblMisPostulaciones.getSelectedRow();
        System.out.println("La fila es: " + fila);

        if (fila != -1) {
            Object titulo = tblMisPostulaciones.getValueAt(fila, 1);
            Object empresa = tblMisPostulaciones.getValueAt(fila, 2);
            Object sueldo = tblMisPostulaciones.getValueAt(fila, 3);
            Object modalidad = tblMisPostulaciones.getValueAt(fila, 4);
            Object descripcion = tblMisPostulaciones.getValueAt(fila, 5);

            StringBuilder descripcionCompleta = new StringBuilder();
            descripcionCompleta.append("================== DESCRIPCIÓN DEL EMPLEO ==================\n\n");
            descripcionCompleta.append("Titulo:  ").append(titulo != null ? titulo.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Empresa:  ").append(empresa != null ? empresa.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Sueldo:  ").append(sueldo != null ? sueldo.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Modalidad:  ").append(modalidad != null ? modalidad.toString() : "No disponible").append("\n\n");
            descripcionCompleta.append("Descripción:  ").append(descripcion != null ? descripcion.toString() : "No disponible").append("\n\n");

            txtPostulacionesDescripcion.setText(descripcionCompleta.toString());
        }
    }//GEN-LAST:event_tblMisPostulacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAptitud;
    private javax.swing.JButton AgregarCertificado;
    private javax.swing.JButton AgregarCurriculum;
    private javax.swing.JButton AgregarExperiencia;
    private javax.swing.JTextField Aptitudes;
    private javax.swing.JTextField Celular;
    private javax.swing.JLabel CurriculumArchivo;
    private javax.swing.JTextField DNI;
    private javax.swing.JComboBox<String> EstadoCivil;
    private javax.swing.JComboBox<String> Estudios;
    private javax.swing.JTextField EstudiosFechaFin;
    private javax.swing.JTextField EstudiosFechaInicio;
    private javax.swing.JTextField Experiencia;
    private javax.swing.JTextField ExperienciaFechaFin;
    private javax.swing.JTextField ExperienciaFechaInicio;
    private javax.swing.JTextField FechaNacimiento;
    private javax.swing.JComboBox<String> Genero;
    private javax.swing.JButton QuitarAptitud;
    private javax.swing.JButton QuitarCertificado;
    private javax.swing.JButton QuitarCurriculum;
    private javax.swing.JButton QuitarEstudios;
    private javax.swing.JButton QuitarExperiencia;
    private javax.swing.JTable TablaExperiencia;
    private javax.swing.JButton btnPostularEmpleos;
    private javax.swing.JButton btnRegistrarEstudioAcademico;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTable tblEmpleos;
    private javax.swing.JTable tblListaEstudiosAcademicos;
    private javax.swing.JTable tblMisPostulaciones;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextArea txtAreaAptitudes;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescripcionEL;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtEmpleoDescripcion;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextArea txtPostulacionesDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
